### ISSUE TITLE
IONIC serve is not working

### ISSUE THREAD

**Issue by sujith-mn** [oasp/oasp4js-ionic-application-template#236]
devon ionic serve  is giving following error while starting

![image](https://user-images.githubusercontent.com/61968717/96866568-1f1cfa80-1489-11eb-9f75-c7f76df17ea1.png)

Below is the stack strace:

[error] TypeError: Cannot read property 'Minus' of undefined
    at C:\Temp\devon4ng-ionic-application-template-develop\node_modules\@angular\compiler-cli\src\ngtsc\translator\src\translator.js:47:37
    at C:\Temp\devon4ng-ionic-application-template-develop\node_modules\@angular\compiler-cli\src\ngtsc\translator\src\translator.js:10:17
    at Object.<anonymous> (C:\Temp\devon4ng-ionic-application-template-develop\node_modules\@angular\compiler-cli\src\ngtsc\translator\src\translator.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at C:\Temp\devon4ng-ionic-application-template-develop\node_modules\@angular\compiler-cli\src\ngtsc\translator\index.js:20:24
    at C:\Temp\devon4ng-ionic-application-template-develop\node_modules\@angular\compiler-cli\src\ngtsc\translator\index.js:10:17
    at Object.<anonymous> (C:\Temp\devon4ng-ionic-application-template-develop\node_modules\@angular\compiler-cli\src\ngtsc\translator\index.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)

**Comment by sjimenez77** [comment]
Solved in #237
